# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160901_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='picture',
            field=models.ImageField(default='/static/img/user.png', upload_to='/static//photo/'),
        ),
    ]
